### ISSUE TITLE
 Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given,

### ISSUE THREAD

**Issue by rajath-ramachandran** [rawilk/laravel-modules#1]
When I'm trying to install the package on Laravel 5.7  via composer, an error occurred
" Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given,"

**Comment by rawilk** [comment]
If you upgrade to Laravel v6 and use v0.3 of this package, you shouldn't get that error.
